# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ea8e94616b4ee2fc5456762ad23b1e9d"
name = "product-data-fetch"
handle = "product-data-fetch"
application_url = "https://discuss-height-greek-trends.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "d-interview-test-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://discuss-height-greek-trends.trycloudflare.com/auth/callback",
  "https://discuss-height-greek-trends.trycloudflare.com/auth/shopify/callback",
  "https://discuss-height-greek-trends.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
